import type { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiHeartDuotone,
  PiCoffeeDuotone,
  PiLightningDuotone,
  PiSparkleDuotone,
  PiGiftDuotone,
  PiMicrophoneStageDuotone,
  PiMapPinDuotone,
  PiClockDuotone,
  PiUsersDuotone,
  PiPlayDuotone,
  PiXBold,
  PiMusicNotesDuotone,
  PiTrainDuotone,
  PiRssDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiBluesky,
  SiTypescript,
  SiSass,
  SiAlgolia,
  SiNuxtdotjs,
  SiVuedotjs,
  SiGreensock,
  SiTailwindcss,
  SiLaravel,
  SiPhp,
  SiAlpinedotjs,
  SiFramer,
  SiSqlite,
  SiReact,
  SiAngular,
  SiSvelte,
  SiSpringboot,
  SiCplusplus,
  SiPython,
  SiGo,
  SiGit,
  SiYoutube,
  SiKofi,
  SiBuymeacoffee,
  SiMastodon,
  SiGitlab,
} from "react-icons/si";

import { FaStar, FaCodeFork, FaClockRotateLeft } from "react-icons/fa6";
import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  star: FaStar,
  "git-fork": FaCodeFork,
  history: FaClockRotateLeft,
  youtube: SiYoutube,
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  bluesky: SiBluesky,
  typescript: SiTypescript,
  sass: SiSass,
  algolia: SiAlgolia,
  nuxt: SiNuxtdotjs,
  vue: SiVuedotjs,
  gsap: SiGreensock,
  tailwind: SiTailwindcss,
  laravel: SiLaravel,
  php: SiPhp,
  alpine: SiAlpinedotjs,
  framer: SiFramer,
  sqlite: SiSqlite,
  reactapi: SiReact,
  heart: PiHeartDuotone,
  coffee: PiCoffeeDuotone,
  bolt: PiLightningDuotone,
  sparkle: PiSparkleDuotone,
  gift: PiGiftDuotone,
  microphone: PiMicrophoneStageDuotone,
  location: PiMapPinDuotone,
  clock: PiClockDuotone,
  people: PiUsersDuotone,
  play: PiPlayDuotone,
  close: PiXBold,
  link: HiOutlineLink,
  angular: SiAngular,
  svelte: SiSvelte,
  springboot: SiSpringboot,
  vocaloid: PiMusicNotesDuotone,
  cpp: SiCplusplus,
  python: SiPython,
  go: SiGo,
  git: SiGit,
  kofi: SiKofi,
  buymeacoffee: SiBuymeacoffee,
  cal: HiCalendarDays,
  train: PiTrainDuotone,
  rss: PiRssDuotone,
  mastodon: SiMastodon,
  gitlab: SiGitlab,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
